import React from 'react';
import Card from './Card';
import { AlertOctagon, CheckCircle2, ShieldAlert } from 'lucide-react';

/**
 * Security Recommendation Card for Page 3 (/results).
 */
export default function RecommendationCard({ recommendation, prediction }) {
  const isSpoof = prediction === 'Spoof';

  return (
    <Card
      title="Security Recommendation"
      subtitle="Actionable protocol guidance generated by FastAPI threat engine"
    >
      <div className={`p-4 border rounded-md ${
        isSpoof
          ? 'bg-red-950/40 border-red-800 text-red-200'
          : 'bg-emerald-950/40 border-emerald-800 text-emerald-200'
      }`}>
        <div className="flex items-start space-x-3">
          {isSpoof ? (
            <ShieldAlert className="w-6 h-6 text-red-400 flex-shrink-0 mt-0.5" />
          ) : (
            <CheckCircle2 className="w-6 h-6 text-emerald-400 flex-shrink-0 mt-0.5" />
          )}

          <div>
            <h4 className="text-xs font-mono font-bold uppercase tracking-wider mb-1">
              {isSpoof ? 'SECURITY WARNING' : 'AUTHENTICATION CLEAR'}
            </h4>
            <p className="text-sm font-sans leading-relaxed font-medium">
              {recommendation || (isSpoof
                ? 'Do not trust the caller. Voice pattern contains synthesis anomalies. Request multi-factor identity verification.'
                : 'Acoustic parameters pass synthetic speech thresholds. Standard identity policy applies.')}
            </p>
          </div>
        </div>
      </div>
    </Card>
  );
}
